name: Tweet Latest Commit/Release

on:
  push:
    branches: [ main, master ]
  release:
    types: [ published ]

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install tweepy

      - name: Post Thread to Twitter
        env:
          X_API_KEY: ${{ secrets.API_KEY }}
          X_API_SECRET: ${{ secrets.API_SECRET }}
          X_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          X_ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: python .github/scripts/post_tweet.py
